.\"Created with GNOME Manpages Editor Wizard
.\"http://sourceforge.net/projects/gmanedit2
.TH mia-gui 1 "April 27, 2015" "" "Mass Isotopolome Analyzer"

.SH NAME
mia-gui \- program for non-targeted mass isotopolome analysis

.SH SYNOPSIS
.B mia-gui
.RI [ options ]
.br

.SH DESCRIPTION
This manual page explains the
.B mia-gui
program. This program...
.PP
\fBmia-gui\fP is for...

.SH OPTIONS
.B
.IP -OPTION
This option...

